### ISSUE TITLE
Remove dependency on lens

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/servant-checked-exceptions#1]
It would be nice to remove the dependency on lens.

We can probably do this in a similar way to the [union](https://hackage.haskell.org/package/union) library:

https://github.com/int-index/union/blob/master/src/Data/Union/Prism.hs

**Comment by TimoFreiberg** [comment]
Used the definitions you linked, added `over` and `(<>~)` from the `lens` code.
#10
