### ISSUE TITLE
Break into combinator/backend packages

### ISSUE THREAD

**Issue by imalsogreg** [cdepillabout/servant-checked-exceptions#25]
We use `servant-checked-exceptions` in the frontend, and would like to avoid a transitive dependency on `servant-server`, `servant-client`, `conduit` etc.

What do you think of having two packages here `servant-checked-exceptions-core` (just types and pure functions) and `servant-checked-exceptions` (instances and functions that depend on server-side code)?

**Comment by cdepillabout** [comment]
Yes, this is definitely a good idea.  I'm actually surprised I didn't have a ticket listing this.

If you or anyone else wanted to get started working on this, I would definitely merge in a PR, or help clean it up.

**Comment by imalsogreg** [comment]
Thanks, I'll get started!

**Comment by cdepillabout** [comment]
@imalsogreg I also have an issue about breaking up stuff that is currently in the `Servant.Checked.Exceptions` module.

https://github.com/cdepillabout/servant-checked-exceptions/issues/18

If doing that would help you with this issue, please feel free to do what is necessary :+1:

**Comment by imalsogreg** [comment]
This is the directory structure I have in mind - trying to stick to the style you are using already:

```
Current:

src/Servant/Checked
 - Exceptions.hs
 - Exceptions
   - Internal.hs
   - Internal
     - Envelope.hs
     - Prism.hs
     - Utils.hs
     - Servant.hs
     - Servant
       - API.hs
       - Client.hs
       - Docs.hs
       - Server.hs

Future:

servant-checked-exceptions-core/src/Servant/Checked
  - Exceptions.hs
  - Exceptions
    - Verbs.hs
    - Envelope.hs
    - Internal.hs
    - Internal
      - Envelope.hs
      - Prism.hs
      - Utils.hs
      - Servant.hs
      - Servant
        - API.hs
        - Docs.hs

servant-checked-exceptinos/src/Servant/Checked
  - Exceptions.hs
  - Exceptions
    - Internal.hs
    - Internal
      - Servant.hs
      - Servant
        - Client.hs
        - Server.hs
```

Open to suggestions! Are you bothered by having to maintain two hackage packages instead of one?
