### ISSUE TITLE
Build failure with servant 0.16

### ISSUE THREAD

**Issue by snoyberg** [cdepillabout/servant-checked-exceptions#29]
```
[3 of 6] Compiling Servant.Checked.Exceptions.Internal.Servant.Server ( src/Servant/Checked/Exceptions/Interna
l/Servant/Server.hs, dist/build/Servant/Checked/Exceptions/Internal/Servant/Server.o )

src/Servant/Checked/Exceptions/Internal/Servant/Server.hs:49:5: error:
    Module
    ‘Servant.Server.Internal.RoutingApplication’
    does not export
    ‘Delayed’
   |
49 |   ( Delayed
   |     ^^^^^^^

src/Servant/Checked/Exceptions/Internal/Servant/Server.hs:50:5: error:
    Module
    ‘Servant.Server.Internal.RoutingApplication’
    does not export
    ‘DelayedIO’
   |
50 |   , DelayedIO
   |     ^^^^^^^^^

src/Servant/Checked/Exceptions/Internal/Servant/Server.hs:51:5: error:
    Module
    ‘Servant.Server.Internal.RoutingApplication’
    does not export
    ‘RouteResult(FailFatal, Route)’
   |
51 |   , RouteResult(FailFatal, Route)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Servant/Checked/Exceptions/Internal/Servant/Server.hs:52:5: error:
    Module
    ‘Servant.Server.Internal.RoutingApplication’
    does not export
    ‘addAcceptCheck’
   |
52 |   , addAcceptCheck
   |     ^^^^^^^^^^^^^^
```

And more

**Comment by imalsogreg** [comment]
@cdepillabout How about I do a quick hackage bounds update to prevent users from accidentally getting `servant-checked-exceptions` with `servant-0.16` for the time being, and then open a ticket to add 0.16 support?

**Comment by imalsogreg** [comment]
@cdepillabout PS (meta) is this the kind of thing you want me to check in with you about, or in general should I feel free to go ahead with any maintainer-ish actions?

**Comment by cdepillabout** [comment]
@imalsogreg Yes, please feel free to go ahead and do a hackage bounds update.

**Comment by imalsogreg** [comment]
https://github.com/cdepillabout/servant-checked-exceptions/issues/30 <- tracking 0.16 support

For now, the metadata rev has limited us to 0.15: https://matrix.hackage.haskell.org/#/package/servant-checked-exceptions
![image](https://user-images.githubusercontent.com/993484/53845559-9847a100-3f77-11e9-8fc7-f8d35660cbfe.png)
